// Generated by Wrangler by running `wrangler types --experimental-include-runtime --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	NEXT_CACHE_WORKERS_KV: KVNamespace;
	ASSETS: Fetcher;
}
