#:schema node_modules/wrangler/config-schema.json
main = ".worker-next/index.mjs"
name = "eskridge"

compatibility_date  = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Use the new Workers + Assets to host the static frontend files
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

observability = { enabled = true }

[[kv_namespaces]]
    binding = "NEXT_CACHE_WORKERS_KV"
    id      = "bc210279e0de4336a888e36976c13ea7"
