#:schema node_modules/wrangler/config-schema.json
main = ".open-next/worker.js"
name = "eskridge"

compatibility_date  = "2024-11-06"
compatibility_flags = ["nodejs_compat"]

# Use the new Workers + Assets to host the static frontend files
assets = { directory = ".open-next/assets", binding = "ASSETS" }

observability = { enabled = true }
