name: "Setup Playwright"
description: "Setup Playwright with caching"

runs:
  using: "composite"
  steps:
    - name: Cache Playwright
      id: playwright-cache
      uses: actions/cache@v4
      with:
        path: ${{ runner.os == 'Windows' && format('{0}{1}', env.HOME, '\AppData\Local\ms-playwright') || runner.os == 'Linux' && '~/.cache/ms-playwright' || '~/Library/Caches/ms-playwright' }}
        key: playwright-${{ runner.os }}-${{ hashFiles('bun.lock') }}

    - name: Install Playwright with dependencies
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: bun x playwright install --with-deps

    - name: Install Playwright's dependencies
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      shell: bash
      run: bun x playwright install-deps